### ISSUE TITLE
Error Contents: No module named 'utils'

### ISSUE THREAD

**Issue by KaiNickson** [jelly/plugin.video.fosdem#16]
When opening the addon in kodi 19.3 the addon closes immediately.
In the log i get the following message:

> 2021-12-16 01:33:14.434 T:4617    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'utils'
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.fosdem/resources/lib/addon_entry.py", line 9, in <module>
                                                       from addon import run
                                                     File "/home/user/.kodi/addons/plugin.video.fosdem/resources/lib/addon.py", line 12, in <module>
                                                       from utils import html_to_kodi
                                                   ModuleNotFoundError: No module named 'utils'
                                                   -->End of Python script error report<--

This is with the version of the add on from the official repo (0.0.6)
When getting the addon directly from github (0.0.7?) everything works, but I wanted to inform about my experience with the currently available version in kodi itself.

**Comment by jelly** [comment]
In matrix the plugin should be 0.0.7 https://github.com/xbmc/repo-plugins/tree/matrix/plugin.video.fosdem

**Comment by jelly** [comment]
Maybe I messed up the update https://github.com/xbmc/repo-plugins/blob/matrix/plugin.video.fosdem/addon.xml#L2

**Comment by diederikdehaas** [comment]
I had this problem too. I don't know to get the addon from github, but `wget https://raw.githubusercontent.com/jelly/plugin.video.fosdem/main/resources/lib/utils.py` in the right directory fixed it for me :-)

Running ~ latest nightly build of LibreELEC which uses kodi 20.ALPHA1 (19.90.101)

**Comment by Ferruck** [comment]
Are there any plans to fix this? Otherwise, I'd might chip in if you don't mind.

**Comment by jelly** [comment]
It should be fixed now in kodi addon repositories. sorry for the long wait.
